name: Deploy on server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_SERVER }} > ~/.ssh/known_hosts

      - name: Copy files using rsync
        run: rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:${{ secrets.WORK_DIR }}

      - name: Deploy using docker compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_SERVER}} "
            cd ${{ secrets.WORK_DIR }} &&
            docker-compose pull &&
            docker-compose up -d --build
          "
